[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "binaryai"
description = """
BinaryAI-SDK is a library provides an abstracted client module \
to simplify the procedure of uploading file for analysis."""
license = {text = "GPLv3"}
authors = [
    {name = "binaryai", email = "binaryai@tencent.com"},
]
requires-python = ">=3.8"
dependencies = [
    "Deprecated",
    "gql[requests]",
    "qcloud-requests-auth",
]
dynamic = ["version"]

[project.urls]
homepage = "https://www.binaryai.cn/"
documentation = "https://www.binaryai.cn/doc/"
repository = "https://github.com/binaryai/sdk/"

[tool.setuptools.packages.find]
include = ["binaryai"]
exclude = ["examples"]

[tool.setuptools_scm]
fallback_version = "0.0.0"
