name: FLAKE8 CHECK

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==4.0.1 black==22.6.0 isort==5.10.1
    - name: Perform linting
      run: |
        flake8 .
        black --check --line-length=120 .
        isort --profile=black --line-length=120 -c .
