name: FLAKE8 CHECK

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set up poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.6'
    - name: Install dependencies
      run: |
        poetry install --with=dev
    - name: Perform linting
      run: |
        poetry run flake8 .
        poetry run black --check --line-length=120 .
        poetry run isort --profile=black --line-length=120 -c .
